### ISSUE TITLE
Why does this repo return promises?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-geodb#30]
As pointed out in https://github.com/mozilla/fxa-content-server/pull/5595#discussion_r145867114, it doesn't appear that this repo does anything async.

Returning promises has knock-on effects in some of our calling code, for instance the `request.app.geo` lazy getter in the auth server is more annoying to use than the other lazy getters because it must be dereferenced via `then`.

If we can change this repo to use synchronous return/throw semantics (and bump the major rev, obviously), we could simplify our calling code.

**Comment by shane-tomlinson** [comment]
Because promises were the amazing future man!

I think the original idea is that before we settled on maxmind, we weren't sure which geo DB we were going to use as the backend. To give maximum flexibility and to be able to develop against something, we used promises in case the final backend load/access was asynchronous. Turns out we didn't need the asynchronous behavior.
